# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nbdev-game',
                'doc_host': 'https://Qwarkster.github.io',
                'git_url': 'https://github.com/Qwarkster/nbdev-game',
                'lib_path': 'nbdev_game'},
  'syms': {'nbdev_game.core': {'nbdev_game.core.foo': ('core.html#foo', 'nbdev_game/core.py')}}}
